---
abstract: "Andrew's monotone chain algorithm for finding a convex hull in 2D"
author:
  - 'Steffen Mueller <smueller@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.58, CPAN::Meta::Converter version 2.110930'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-ConvexHull-MonotoneChain
no_index:
  directory:
    - t
    - inc
requires:
  Data::Dumper: 0
  Test::More: 0.88
version: 0.01
